FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /backend

RUN apt-get update && \
    apt-get install -y netcat-openbsd && \
    apt-get clean && \
    pip install gunicorn==23.0.0

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

COPY . .

COPY startapp.sh /startapp.sh
RUN chmod +x /startapp.sh

ENTRYPOINT ["/startapp.sh"]
