# Generated by Django 5.2.3 on 2025-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='shard',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
