# Generated by Django 5.2.3 on 2025-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_url_category_shard'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='query',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='shard',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
