volumes:
  postgres_data:
  static:
  redis_data:

services:
  db:
    image: postgres:15
    container_name: wb_db
    volumes:
      - postgres_data:/home/tyunkov/develop/django/WBAlytics
    env_file:
      - .env

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - static:/static
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
